Provide basic macOS support #30
filips123/FirefoxPWA pull request #31
Opened 2021-07-10 21:56 UTC by TitanNano

Closes #30. 

This does not yet update the installation instructions for macOS. 
I'm not sure what the best way for installation on macOS would be. Installing via Homebrew would probably be the most convenient way for many people. I have no idea what submitting this project to Homebrew would involve, though.  Providing a prebuilt ZIP file with all the necessary binaries and assets might also work well enough.

2021-07-11 10:26 UTC, filips123 commented
Thanks for the PR!

For installation, I was thinking of using APP/DMG/PKG bundle (I'm not sure what the differences are and which one is appropriate, if any) and/or some of [macOS' package managers](https://apple.stackexchange.com/a/34972). I haven't done much research about this yet, so I'm not sure what doing this would involve, and if it's actually possible.

A few things I'm worried about are permissions (because runtime currently needs to be installed globally, which needs root permissions and I'm not sure how macOS handles that; however, I'm planning to also allow user-specific runtime installation which may solve this issue) and app sandboxing (AFAIK macOS has some app sandbox, and I'm not sure if it conflicts with runtime installation and launching, and using native messaging).

2021-07-11 14:02 UTC, TitanNano commented
DMG is just a disc image format and is usually used to distribute GUI applications as they consist of only a single app bundle, which can be dragged and dropped into the global Applications directory of macOS.

APP is a simple directory with a `.app` extensions, which contains all the necessary binaries and static resources that are needed by an Application (icons, translations, images, etc.). It is almost never used by CLI applications, as it's really designed for GUI apps.

PKG can be compared to an MSI on Windows. It's an installation wizard, usually used by more complex applications that require system extensions or something similar and are not just one single app bundle. A PKG could be used for this project to provide a GUI based installation workflow. I think macOS might be required to build a PKG package, though. 

Homebrew is the de facto standard package manager on macOS. It also takes care of the permission issues as `/usr/local` is taken over and managed by Homebrew, so no superuser permissions are required to install or run Homebrew formulas. [Here](https://docs.brew.sh/Formula-Cookbook) is a guide on how to publish something to the repo. 

But as a first step I'd start with letting people build and install from source on macOS and then when everything works out, in a next step, some automatic installation can be figured out.

I will go ahead and update this PR to contain proper `install from source` instructions and fix the CI issues.

2021-07-12 17:21 UTC, filips123 requested changes
This PR mostly looks fine, but there are a few changes that should be made. Also, please uncomment [clippy check for macOS](https://github.com/filips123/FirefoxPWA/blob/main/.github/workflows/native.yaml#L29) for GitHub Actions. I will probably merge PR this weekend, because I don't have time until Friday and still need to do a few things.

---

Also, for the record, these features are needed to fully support macOS in the future:

* Packaging (I will probably be able to do this myself)
  * PKG installer (maybe)
  * Homebrew formula (and maybe also packages for other package managers)

* System integration (basically the things that are already in Windows and Linux integrations; I will probably need some help here)
  * When installing PWA site
    * It needs to create an application shortcut/entry with a required icon, name, description, keywords and categories (if macOS doesn't support some of those properties, it's fine, but it needs at least an icon and name) that launches the site.
    * It should also add shortcuts/links to the entry with actions from the manifest. I don't know if this is supported on macOS or how is it called, but on Windows these are jump list tasks and on Linux desktop actions. This functionality is not needed as much as others, so it can be added later.
    * That entry needs to be added to the user-specific app menu/list. I think this could be done by creating a custom `.app` bundle with all those properties that is installed to `~/Applications`.
    * If macOS has some way to list/manage/uninstall apps (such as Add or Remove Programs page in Windows), the site should be registered there, so the user can uninstall it directly from the system.
  * When uninstalling PWA site
    * All system integration entries should be removed.
  * When launching PWA site
    * The window should have a correct site icon. Maybe this can be done in app entry, maybe it also needs some configuration at run-time.
    * The window should not merge/group with other Firefox and PWA windows. On Windows, this is done using Application User Model ID, and on Linux it uses `--class` command argument when launching Firefox to set `WM_CLASS`.
  * *Maybe I also forgot something that is done for Windows and Linux and should also be done here.*

2021-07-12 20:25 UTC, TitanNano commented on native/README.md
> +sudo install -v manifests/macos.json /Library/Application\ Support/Mozilla/NativeMessagingHosts/firefoxpwa.json
`-D` is not supported on macOS

2021-07-19 10:20 UTC, filips123 approved these changes
I just fixed setting versions, converted the warning to HTML and added some CSS changes.  Now it seems all right. Thanks for the help!

2021-07-19 10:26 UTC, merged